#!/usr/bin/env perl
# version 0003
# updated 2022-04-04T14:56:11-07:00
use v5.30.0;
my $nexo_csv_file = $ARGV[0] or die "Please supply Nexo CSV file";
open( my $fh_csv, '<', $nexo_csv_file ) or die "$!: Can't find $nexo_csv_file";
open( my $fh_warnings, '>', 'WARNINGS' ) or warn "$!: Unable to open WARNINGS file";

my $header_line = <$fh_csv>; # Through away the Nexo column header line

my $new_header_line = "Date,Sent Amount,Sent Currency,Received Amount,Received Currency,Label,TxHash,Description,TxHash,TxNexo,Type";
# say "$date_time_with_tz,$output_amount,$output_currency,$input_amount,$input_currency,$label,$description,$TxHash";

say $new_header_line;

while(my $row = <$fh_csv>) {
    chomp $row;
    my $label;
    next if $row =~ /LockingTermDeposit/;
    next if $row =~ /UnlockingTermDeposit/;
    my ($nexo_transaction,$type,$input_currency,$input_amount,$output_currency,$output_amount,$usd_equivalent,$details,$outstanding_loan,$nexo_date_time) = split /,/, $row;
    my ($description, $tx_hash);
    my ($description,$tx_hash) = get_description($type, $details, $nexo_transaction);
    my $date_time_with_tz = date_with_timezone($nexo_date_time);

    ($input_currency,$input_amount ) = fix_exchange($input_currency, $input_amount) if ($type eq 'Exchange');

    if (($type eq 'Deposit') or	($type eq 'Exchange Cashback')) {
	($output_currency, $output_amount)  = ('', '');
    } elsif ($type eq 'Withdrawal') {
	($input_currency, $input_amount) = ('', '');
    } elsif (($type eq 'Interest') or ($type eq 'FixedTermInterest')) {
	$label = 'Loan Interest';
	($output_currency, $output_amount)  = ('', '');
    } elsif ($type eq 'TransferIn') {
	($output_currency, $output_amount)  = ('', '');
    } elsif ($type eq 'TransferOut') {
	($input_currency, $input_amount)  = ('', '');
    }
    say "$date_time_with_tz,$output_amount,$output_currency,$input_amount,$input_currency,$label,$tx_hash,$description,$nexo_transaction,$type";
}

sub fix_exchange {
    my ( $input_currency, $input_amount ) = @_;
    $input_currency =~ s/\/\w+//;
    $input_amount = '???';
    return($input_currency, $input_amount);
}

sub date_with_timezone {
    my $nexo_date = shift;
    return $nexo_date . '+01:00'
}

sub get_description {
    my ($type, $details, $nexo_transaction) = @_;
    my $tx_hash = '';
    # approved / 
    my $description = $details;
    $description =~ s/(^approved \/ )//;
    if ($1 ne 'approved / ') {
	warn "warning: not approved";
	say $fh_warnings "$nexo_transaction not approved";
    }
    if ($type eq 'Deposit') {
	unless ($description =~ /(\s)/) {
	    if (length($description) > 16) {
		$tx_hash = $description;
		$description = '';
	    }
	}
    }
    return ($description,$tx_hash);
}
