#!/usr/bin/env perl
# version 0001
use v5.30.0;
my $nexo_csv_file = $ARGV[0] or die "Please supply Nexo CSV file";
open( my $fh_csv, '<', $nexo_csv_file ) or die "$!: Can't find $nexo_csv_file";
my $header_line = <$fh_csv>; # Through away the Nexo column header line

my $new_header_line = "Date,Sent Amount,Sent Currency,Received Amount,Received Currency,Label,TxHash";
say $new_header_line;

while(my $row = <$fh_csv>) {
    chomp $row;
    my $label;
    next if $row =~ /LockingTermDeposit/;
    next if $row =~ /UnlockingTermDeposit/;
    my ($nexo_transaction,$type,$input_currency,$input_amount,$output_currency,$output_amount,$usd_equivalent,$details,$outstanding_loan,$nexo_date_time) = split /,/, $row;
    my $date_time_with_tz = date_with_timezone($nexo_date_time);

    ($input_currency,$input_amount ) = fix_exchange($input_currency, $input_amount) if ($type eq 'Exchange');

    if (($type eq 'Deposit') or ($type eq 'Exchange Cashback') ) {
	$output_currency = '';
	$output_amount = '';
    } elsif ($type eq 'Withdrawal') {
	$input_currency = '';
	$input_amount = '';
    }

    if (($type eq 'Interest') or ($type eq 'FixedTermInterest')) {
	$label = 'Loan Interest';
	$output_currency = '';
	$output_amount = '';
    }

    say "$date_time_with_tz,$output_amount,$output_currency,$input_amount,$input_currency,$label";
}

sub fix_exchange {
    my ( $input_currency, $input_amount ) = @_;
    $input_currency =~ s/\/\w+//;
    $input_amount = "=> MANUAL";
    return($input_currency, $input_amount);
}

sub date_with_timezone {
    my $nexo_date = shift;
    return $nexo_date . '+01:00'
}
