* Introduction
  + Updated 2022-04-03T00:33:19-07:00
  + This is a utility written in Perl to fix and reformat a Nexo transaction CSV export to a CSV file readable by Koinly.
  + It is necessary as of 2022-04-02T23:44:30-07:00. Ideally the need for this program will be very short lived!
  + This program was written by following the excellent Koinly documentation at
  https://help.koinly.io/en/articles/3662999-how-to-create-a-custom-csv-file-with-your-data
  You can see a Koinly template at https://docs.google.com/spreadsheets/d/1dESkilY70aLlo18P3wqXR_PX1svNyAbkYiAk2tBPJng/edit#gid=0

** This program fixes 3 problems in the Nexo CVS export.

*** Problem 1: Duplicate data fields in Deposits and Withdrawals.
    Here is a data row in a Nexo CVS deposit transaction (edited for readability)
    | Transaction | Type    | Input Currency |  Input Amount | Output Currency | Output Amount |
    |-------------+---------+----------------+---------------+-----------------+---------------+
    | NXT.......M | Deposit | MATIC          | 1882.25266872 | MATIC           | 1882.25266872 |

    Nexo incorrectly populates the Output Currency and Amount. A deposit transaction has no output.

    Here's the same data row after processed by my program:
    | Transaction | Type    | Input Currency |  Input Amount | Output Currency | Output Amount |
    |-------------+---------+----------------+---------------+-----------------+---------------|
    | NXT.......M | Deposit | MATIC          | 1882.25266872 |                 |               |

    This transaction will now load into Koinify because Output Currency and Output Amount are empty.
*** Problem 2: Improper and incorrect fields in exchange transactions
    Here is a data row in a Nexo CVS exchange transaction (edited for readability)
    | Transaction | Type     | Input Currency | Input Amount   | Output Currency | Output Amount |
    |-------------+----------+----------------+----------------+-----------------+---------------+
    | NXT.......r | Exchange | USDC/BNB       | BNB 2.45493262 | BNB             |    2.45493262 |
    Nexo garbles the Input Currency field and puts garbage in the input amount.
    Here's the same data row after processed by my program:
    | Transaction | Type     | Input Currency | Input Amount | Output Currency | Output Amount |
    |-------------+----------+----------------+--------------+-----------------+---------------|
    | NXT.......r | Exchange | USDC           | => MANUAL    | BNB             |    2.45493262 |
    Please notice my program puts a "=> MANUAL" placeholder into the 'Input Amount' field. This is to indicate
    the that you have to look up the input amount on your transactions page in your Nexo web interface and manually
    enter this value into the CSV file row of the CSV file produced by my program.
*** Problem 3: Nexo's undocumented use of Central European Time (CET) time zone.
    Nexo expects time values in UST time. Nexo uses CET time.
    Here is a data row in a Nexo CVS deposit transaction (edited for readability)
    | Date / Time         | Transaction | Type    |
    |---------------------+-------------+---------|
    | 2022-03-28 18:49:14 | NXT.......M | Deposit |
    Note that Nexo doesn't indicate the timezone even thought it is using a non standard CET time zone for the 'Date / Time' field.
    Here's the same data row after processed by my program:
    | Date / Time               | Transaction | Type    |
    |---------------------------+-------------+---------|
    | 2022-03-28 18:49:14+01:00 | NXT.......M | Deposit |


** Data field mapping from Nexo to Koinify
   Here are the data fields in the current Nexo CSV format (edited for readability):
   | Transaction | Type | Currency | Amount | USD Equivalent | Details | Outstanding Loan | Date / Time |
* The nexo-koinly-cvs Perl program
  #+begin_src perl :tangle nexo-koinly-cvs :shebang #!/usr/bin/env perl
    # version 0001
    use v5.30.0;
    my $nexo_cvs_file = $ARGV[0] or die "Please supply Nexo CVS file";
    open( my $fh_cvs, '<', $nexo_cvs_file ) or die "$!: Can't find $nexo_cvs_file";
    my $header_line = <$fh_cvs>; # Through away the Nexo column header line

    my $new_header_line = "Date,Sent Amount,Sent Currency,Received Amount,Received Currency,Label,TxHash";
    say $new_header_line;

    while(my $row = <$fh_cvs>) {
	chomp $row;
	my $label;
	next if $row =~ /LockingTermDeposit/;
	next if $row =~ /UnlockingTermDeposit/;
	my ($nexo_transaction,$type,$input_currency,$input_amount,$output_currency,$output_amount,$usd_equivalent,$details,$outstanding_loan,$nexo_date_time) = split /,/, $row;
	my $date_time_with_tz = date_with_timezone($nexo_date_time);

	($input_currency,$input_amount ) = fix_exchange($input_currency, $input_amount) if ($type eq 'Exchange');

	if (($type eq 'Deposit') or ($type eq 'Exchange Cashback') ) {
	    $output_currency = '';
	    $output_amount = '';
	} elsif ($type eq 'Withdrawal') {
	    $input_currency = '';
	    $input_amount = '';
	}

	if (($type eq 'Interest') or ($type eq 'FixedTermInterest')) {
	    $label = 'Loan Interest';
	    $output_currency = '';
	    $output_amount = '';
	}

	say "$date_time_with_tz,$output_amount,$output_currency,$input_amount,$input_currency,$label";
    }

    sub fix_exchange {
	my ( $input_currency, $input_amount ) = @_;
	$input_currency =~ s/\/\w+//;
	$input_amount = "=> MANUAL";
	return($input_currency, $input_amount);
    }

    sub date_with_timezone {
	my $nexo_date = shift;
	return $nexo_date . '+01:00'
    }
  #+end_src
